"""Extract Welltris game tables from original/welltris.exe into core/wt_tables.c."""
import os, struct, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import wt

w, ds, img = wt.w, wt.ds, wt.img


def words(off, n): return [w(off + 2 * k) for k in range(n)]
def arr(vals, per=16): return ',\n    '.join(', '.join(str(v) for v in vals[i:i + per]) for i in range(0, len(vals), per))
def code_imm16(addr, opcode):
    """Immediate of the instruction at addr, checked against its expected encoding."""
    assert bytes(img[addr:addr + len(opcode)]) == opcode, f'unexpected code at {addr:04x}'
    return struct.unpack('<H', img[addr + len(opcode):addr + len(opcode) + 2])[0]


# clear_well (1bff) points piece_sets (ds:130c) at the four piece classes
sets = [code_imm16(0x1c03 + 10 * k, bytes([0xc7, 0x06, 0x0c + 4 * k, 0x13])) for k in range(4)]
base = sets[0]
rec_size, count = words(0x01fe, 4), words(0x0206, 4)
end = sets[3] + rec_size[3] * count[3]
assert end == 0x01fd and all(sets[k] + rec_size[k] * count[k] == sets[k + 1] for k in range(3))
blob = list(ds(base, end - base))

# score tables: lines (ds:0216), level (ds:0224) and class (ds:022e) are adjacent words; the
# lines index can run past its table, so they are kept as one array
score = words(0x0216, 16)
speedup = list(ds(0x0038, 4))
fall0 = code_imm16(0x579b, bytes([0xc7, 0x06, 0x26, 0x00]))      # options_menu: fall_delay = 0x119

out = ['/* Generated by re/tools/gen_tables.py from original/welltris.exe. Do not edit. */',
       '/* clang-format off */', '#include "wt_tables.h"', '',
       f'/* ds:{base:04x}: piece records {{colour, info, direction codes..., 0}}, addressed by offset */',
       f'const uint8_t wt_piece_data[{len(blob)}] = {{\n    {arr(blob)}\n}};',
       f'const uint16_t wt_class_offset[4] = {{ {arr([s - base for s in sets])} }};',
       f'const uint16_t wt_class_rec_size[4] = {{ {arr(rec_size)} }};',
       f'const uint16_t wt_class_count[4] = {{ {arr(count)} }};',
       '/* ds:0216: score per lines (index n), per level (index 7 + level), per class (12 + class) */',
       f'const uint16_t wt_score_words[16] = {{ {arr(score)} }};',
       f'const uint8_t wt_level_speedup[4] = {{ {arr(speedup)} }};',
       f'const uint16_t wt_fall_delay0 = {fall0};', '']
hdr = ['/* Generated by re/tools/gen_tables.py from original/welltris.exe. Do not edit. */',
       '#ifndef WT_TABLES_H', '#define WT_TABLES_H', '', '#include <stdint.h>', '',
       f'#define WT_PIECE_DATA_SIZE {len(blob)}', '',
       'extern const uint8_t wt_piece_data[WT_PIECE_DATA_SIZE];',
       'extern const uint16_t wt_class_offset[4];', 'extern const uint16_t wt_class_rec_size[4];',
       'extern const uint16_t wt_class_count[4];', 'extern const uint16_t wt_score_words[16];',
       'extern const uint8_t wt_level_speedup[4];', 'extern const uint16_t wt_fall_delay0;', '',
       '#endif', '']
root = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', 'core')
open(os.path.join(root, 'wt_tables.c'), 'w').write('\n'.join(out))
open(os.path.join(root, 'wt_tables.h'), 'w').write('\n'.join(hdr))
print('wrote core/wt_tables.c, core/wt_tables.h')
