/* Generated by re/tools/gen_tables.py from original/welltris.exe. Do not edit. */
#ifndef WT_TABLES_H
#define WT_TABLES_H

#include <stdint.h>

#define WT_PIECE_DATA_SIZE 251

extern const uint8_t wt_piece_data[WT_PIECE_DATA_SIZE];
extern const uint16_t wt_class_offset[4];
extern const uint16_t wt_class_rec_size[4];
extern const uint16_t wt_class_count[4];
extern const uint16_t wt_score_words[16];
extern const uint8_t wt_level_speedup[4];
extern const uint16_t wt_fall_delay0;

#endif
