# Write art_data.c: the embedded local assets (or empty slots). -DDIR=assets dir (may be empty)
set(NAMES title setup scene1 scene2 scene3 scene4 scene5 well1 well2 hiscore1 hiscore2 dialog credits)
set(OUTC "#include <stddef.h>\n")
set(PTRS "")
set(LENS "")
foreach(N ${NAMES})
  set(F "")
  if(DIR)
    if(EXISTS ${DIR}/${N}.jpg)
      set(F ${DIR}/${N}.jpg)
    elseif(EXISTS ${DIR}/${N}.png)
      set(F ${DIR}/${N}.png)
    endif()
  endif()
  if(F)
    file(READ ${F} HEX HEX)
    string(LENGTH "${HEX}" L)
    math(EXPR L "${L} / 2")
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," BYTES "${HEX}")
    string(APPEND OUTC "static const unsigned char a_${N}[] = {${BYTES}};\n")
    string(APPEND PTRS "a_${N}, ")
    string(APPEND LENS "${L}, ")
  else()
    string(APPEND PTRS "NULL, ")
    string(APPEND LENS "0, ")
  endif()
endforeach()
string(APPEND OUTC "const unsigned char *const art_blob[13] = { ${PTRS} };\nconst int art_blob_len[13] = { ${LENS} };\n")
file(WRITE ${OUT} "${OUTC}")
